---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  destination:
    namespace: mon
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 1.8.0
    chart: alertmanager
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: csi-cephfs-sc
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
...
