---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: kubernetes-project/argocd/cluster-issuers
    repoURL: https://github.com/otus-kuber-2023-08/ShamrockOo4tune_platform.git
    targetRevision: kubernetes-project
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
...
