---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: elasticsearch
  namespace: argocd
spec:
  destination:
    namespace: log 
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://github.com/otus-kuber-2023-08/ShamrockOo4tune_platform.git
    targetRevision: kubernetes-project
    path: kubernetes-project/argocd/efk/elasticsearch
    helm:
      values: |
        volumeClaimTemplate:
          accessModes: ["ReadWriteOnce"]
          storageClassName: csi-cephfs-sc
          resources:
            requests:
              storage: 5Gi
        image: "shamrockoo4tune/elasticsearch"
        imageTag: "8.5.1"
        secret:
          enabled: true
          password: "elastic"
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
...
