---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: fluent-bit
  namespace: argocd
spec:
  destination:
    namespace: log 
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.43.0
    chart: fluent-bit
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
...
