---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: node-exporter
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.29.0
    chart: prometheus-node-exporter
    helm:
      values: |
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
            operator: "Exists" 
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
...
