---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-ingress
  namespace: istio-ingress
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
...
