---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-ingress
  labels:
    app: istio-ingress
    istio: ingress
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: status-port
      nodePort: 30021
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 30443
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: istio-ingress
    istio: ingress
  sessionAffinity: None
  type: LoadBalancer
...
