---
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/otus-kuber-2023-08/ShamrockOo4tune_platform.git
    targetRevision: kubernetes-project
istio:
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.16.1
...
