---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.2.0
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - values/prometheus-values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
...
