---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: istio-ingress
    app.kubernetes.io/instance: istio-ingress
  name: istio-ingress
  namespace: argocd
spec:
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes-project/applications/istio-ingress
    repoURL: https://github.com/otus-kuber-2023-08/ShamrockOo4tune_platform.git
    targetRevision: kubernetes-project    
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
...